name:                assignment3
version:             0.1.0.0
github:              "hendrikdevloed/assignment3"
license:             BSD3
author:              "Hendrik De Vloed"
maintainer:          "example@example.com"
copyright:           "2021 Hendrik De Vloed"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/githubuser/assignment3#readme>

dependencies:
- base >= 4.7 && < 5

library:
  source-dirs: src

executables:
  assignment3-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - assignment3

tests:
  assignment3-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - assignment3
